@startuml Diagrama de Classe

' cores amarelo #fbfdb8 , vermelho #ffa19c, verde #a3fcb9, azul #a7d7d7
package "Core" {
    package "Domain" #fbfdb8d9 {
        package "Validation" {
            class DomainValidation {
                + {static} void notNull(string value, string exceptionMessage = null)
                + {static} void strMaxLength(string $value, int $maxLength = 255, string $message = null)
                + {static} void strMinLength(string $value, int $minLength = 10, string $message = null)
            }
        }

        package "Exceptions"{
            exception EntityValidationException {

            }
        }

        package "Entity"{
            ' - private #protected +public ~package private

            package "Traits" {
                abstract class MagicMethodsTrait {
                    mixed __get()
                }
            }

            class Category {
                - string id
                - string name
                - string description
                - boolean name
                + void activate()
                + void disable()
                + void update(string name, string description)
                + void validate()
            }
        }
    }
}

Category ..> "uses" MagicMethodsTrait
Category ..> "uses" DomainValidation

Category ..> "throws" EntityValidationException
@enduml